services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: releaseradar
      POSTGRES_USER: releaseradar
      POSTGRES_PASSWORD: releaseradar
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U releaseradar -d releaseradar"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database Migration
  db-migrate:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=postgresql://releaseradar:releaseradar@db:5432/releaseradar
    depends_on:
      db:
        condition: service_healthy
    command: ["npx", "prisma", "db", "push"]
    volumes:
      - .:/app
      - /app/node_modules

  # Release Radar Development
  release-radar-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=development
      - PORT=9002
      - DATABASE_URL=postgresql://releaseradar:releaseradar@db:5432/releaseradar
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    stdin_open: true
    tty: true


volumes:
  postgres_data_dev: