services:
  release-radar-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=development
      - PORT=9002
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    stdin_open: true
    tty: true
